version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Blog
      - SPRING_DATASOURCE_USERNAME=perfectoz
      - SPRING_DATASOURCE_PASSWORD=12345manu
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=perfectoz
      - POSTGRES_PASSWORD=12345manu
      - POSTGRES_DB=Blog